<a href="https://colab.research.google.com/github/Isha1600/Python_Projects_Portfolio/blob/main/Day1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [5]:
a = np.array([1,2,3])
print(a * 2)

[2 4 6]


In [6]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(a)
print(a * 3)

[10 20 30 40]
[ 30  60  90 120]


In [8]:
a = np.array([5, 10, 15])
b = np.array([2,4,6])
print(a)
print(b)
print(a + b)

[ 5 10 15]
[2 4 6]
[ 7 14 21]


In [9]:
matrix = np.array([[1,2],
                   [3,4]])
print(matrix)
print(5 * matrix)

[[1 2]
 [3 4]]
[[ 5 10]
 [15 20]]
